theme: minima
title: C. Cardea
description: A simple and useful project for keeping time records.
#header_pages: 
author:
  name: C. Cardea
  email: ccardea@gmail.com

social_links:
  github: ccardea/stt