title: C. Cardea
site:
  author:
    name: C. Cardea
    email: "ccardea@gmail.com"
description: Demonstrating Useful Skills.
#header_pages: 

theme: minima

minima:
  social_links:
    github: ccardea